name = "gpm-email-worker"
main = "workers/emailWorker.js"
compatibility_date = "2023-10-30"
compatibility_flags = ["durable_object_alarms"]

[durable_objects]
bindings = [
  { name = "EMAIL_CAMPAIGN", class_name = "EmailCampaignDurableObject" }
]

[[migrations]]
tag = "v1"
new_classes = ["EmailCampaignDurableObject"]

[vars]
AWS_REGION = "us-east-1"
EMAIL_PROVIDER = "ses"
TRACKING_URL = "https://trk.gravitypointmedia.com"

# Production environment
[env.production]
kv_namespaces = [
  { binding = "GPM_EMAIL_TRACKING", id = "93e0cd15ee104d4fad6532fd73eabd96" }
]

[env.production.vars]
AWS_REGION = "us-east-1"
EMAIL_PROVIDER = "ses"
TRACKING_URL = "https://trk.gravitypointmedia.com"

[env.production.durable_objects]
bindings = [
  { name = "EMAIL_CAMPAIGN", class_name = "EmailCampaignDurableObject" }
]

# Development environment - use different KV namespaces for testing
[env.development]
kv_namespaces = [
  { binding = "EMAIL_TRACKING", id = "xxxx" } # Replace with dev KV ID
]

# Configure the rate limiter to prevent abuse
[env.production.rate_limits]
request_limit = 100   # Requests per minute
batch_limit = 50      # Email batch size

# Analytics and monitoring
usage_model = "bundled"
logpush = true 